/*
 * data.h
 *
 * This header file contains the raw training data for the Very Small Language Model (VSLM).
 * The data is stored in a 2-dimensional vector "raw_data", where each row represents a "document"
 * and each column contains a specific document for the VSLM model training.
 *
 * Note: The data provided here is synthetic and may not necessarily be accurate, as it is intended
 * for the initial training of the model and/or internal tests.
 */

#ifndef DATA_H
#define DATA_H

#include <locale>
#include <codecvt>
#include <iomanip>
#include <iostream>
#include <string>
#include <vector>

using namespace std;

const string shakespeare_test = R"(HAMLET By William Shakespeare
(...)
I'll tent him to the quick: if he but blench,
I know my course. The spirit that I have seen
May be the devil: and the devil hath power
To assume a pleasing shape; yea, and perhaps
Out of my weakness and my melancholy,
As he is very potent with such spirits,
Abuses me to damn me: I'll have grounds
More relative than this: the play's the thing
Wherein I'll catch the conscience of the king.

- Act Three, Scene One
To be or not to be-that is the quest)";

const string shakespeare_text = R"(HAMLET By William Shakespeare
(...)
I'll tent him to the quick: if he but blench,
I know my course. The spirit that I have seen
May be the devil: and the devil hath power
To assume a pleasing shape; yea, and perhaps
Out of my weakness and my melancholy,
As he is very potent with such spirits,
Abuses me to damn me: I'll have grounds
More relative than this: the play's the thing
Wherein I'll catch the conscience of the king.

- Act Three, Scene One
To be or not to be-that is the question:
Whether 'tis nobler in the mind to suffer
The slings and arrows of outrageous fortune,
Or to take arms against a sea of troubles
And, by opposing, end them. To die, to sleep-
No more-and by a sleep to say we end
The heartache and the thousand natural shocks
That flesh is heir to-'tis a consummation
Devoutly to be wished. To die, to sleep-
To sleep, perchance to dream. Ay, there's the rub,
For in that sleep of death what dreams may come,
When we have shuffled off this mortal coil,
Must give us pause. There's the respect
That makes calamity of so long life.
For who would bear the whips and scorns of time,
Th' oppressor's wrong, the proud man's contumely,
The pangs of despised love, the law's delay,
The insolence of office, and the spurns
That patient merit of the unworthy takes,
When he himself might his quietus make
With a bare bodkin? Who would fardels bear,
To grunt and sweat under a weary life,
But that the dread of something after death,
The undiscovered country from whose bourn
No traveler returns, puzzles the will
And makes us rather bear those ills we have
Than fly to others that we know not of?
Thus conscience does make cowards of us all,
And thus the native hue of resolution
Is sicklied o'er with the pale cast of thought,
And enterprises of great pith and moment
With this regard their currents turn awry
And lose the name of action.-Soft you now,
The fair Ophelia.-Nymph, in thy orisons
Be all my sins remembered.)";

std::vector<string> raw_data = {
    R"(Understanding conversational dynamics is fundamental to human interaction. When two people engage in dialogue, they follow implicit turn-taking rules. The speaker holds the floor while expressing their thoughts, using verbal and non-verbal cues to signal when they're finished. The listener demonstrates active engagement through backchanneling - nodding, saying "mm-hmm", or providing brief supportive responses. This dance of conversation helps build rapport and mutual understanding. Pauses and silence also play important roles, giving participants time to process information and formulate responses. The pacing of exchanges tends to find a natural rhythm, with turns typically lasting 2-3 seconds on average. When conversations flow smoothly, participants unconsciously synchronize their speaking patterns, vocal qualities, and even breathing rates - a phenomenon known as conversational entrainment.)",
    R"(Communication involves much more than just words. Non-verbal signals make up 60-70% of meaning in face-to-face interactions. Facial expressions convey emotions: smiles signal happiness, furrowed brows show confusion or concern. Body language speaks volumes - crossed arms may indicate defensiveness, while an open posture suggests receptivity. Gestures naturally accompany and enhance speech. We point to objects we reference, mime actions we describe. Voice carries rich information through prosody - the melody, rhythm, and stress patterns of speech. Changes in pitch, volume, and speaking rate convey emphasis, emotional state, and conversational intent. For example, rising intonation typically signals a question, while falling pitch generally marks the end of a statement. These paralinguistic features help listeners interpret the full meaning of utterances.)",
    R"(Empathy forms the foundation of meaningful human connection. It involves understanding and sharing the feelings of others. Cognitive empathy refers to intellectually grasping another's emotional state and perspective. Affective empathy means actually experiencing echoes of their feelings. Empathetic responses validate emotions: "That must be really difficult" or "I can see why you'd feel that way." Active listening demonstrates empathy through focused attention, appropriate feedback, and checking understanding. Empathy allows us to build trust, provide emotional support, and navigate conflicts constructively. It requires setting aside our own viewpoint temporarily to fully appreciate another's reality. Regular practice of empathy strengthens our capacity for compassionate connection.)",
    R"(The art of asking questions drives engaging dialogue. Open questions beginning with what, how, or why invite detailed responses and deeper exploration. Closed questions eliciting yes/no answers help confirm specific points. Follow-up questions show interest and draw out additional insights: "Can you tell me more about that?" or "How did that make you feel?" Strategic question sequences move from general to specific, concrete to abstract. Leading questions containing assumptions should be avoided. The timing and tone of questions matter as much as content. Questions posed with genuine curiosity and appropriate pacing build rapport and keep conversations flowing naturally.)",
    R"(Memory and learning shape our conversational abilities. Working memory holds immediate context - tracking the thread of discussion, remembering points to respond to. Long-term memory stores our accumulated knowledge, experiences, and social scripts that guide interactions. The spacing effect shows that information is better retained when reviewed at increasing intervals. Emotion strongly influences memory formation - we better remember conversations with high emotional resonance. Active recall through summarizing and rephrasing enhances learning. Making connections between new and existing knowledge aids integration and retention. Regular conversation practice strengthens neural pathways supporting fluent communication.)",
    R"(Context and social awareness critically influence communication. Cultural backgrounds shape conversational norms - acceptable topics, turn-taking patterns, physical proximity, eye contact. Professional settings typically require more formal language and structured exchanges than casual contexts. Group dynamics affect participation patterns and topic selection. Power differentials between speakers impact directness and deference. Environmental factors like noise levels, seating arrangements, and time constraints shape interactions. Skillful communicators adapt their style to suit different contexts while maintaining authenticity. Reading social cues helps gauge appropriate contributions to any conversation.)",
    R"(Small talk serves important social functions despite seeming superficial. Light conversation about weather, sports, or shared experiences helps establish common ground. It eases people into interaction before deeper engagement. Small talk provides practice in turn-taking, topic management, and social norms. It allows participants to gauge each other's mood and receptivity to further interaction. Even brief exchanges can build rapport and social connection. While some view small talk as meaningless, it oils the wheels of social interaction. The skill of engaging in comfortable small talk smooths many daily interactions.)",
    R"(Building rapport requires consistent demonstration of key qualities. Trustworthiness shows through keeping confidences and following through on commitments. Authenticity means being genuinely ourselves while respecting social contexts. Active listening demonstrates valued attention through appropriate verbal and non-verbal feedback. Showing appropriate vulnerability can deepen connections. Finding common ground through shared interests or experiences creates bonds. Respecting boundaries while remaining warm and open maintains comfortable rapport. Regular positive interactions accumulate to create lasting rapport. Small consistent behaviors matter more than grand gestures in relationship building.)",
    R"(Disagreement and conflict are natural parts of human interaction. Healthy conflict management begins with staying calm and focusing on issues rather than personal attacks. Using "I" statements expresses feelings without accusation: "I feel frustrated when..." rather than "You always..." Active listening helps understand other viewpoints even in disagreement. Looking for points of agreement provides foundation for resolution. Compromise involves both parties adjusting positions to find mutually acceptable solutions. Some differences may remain unresolved while maintaining respectful relationships. The goal is handling conflict constructively rather than avoiding it entirely.)",
    R"(Humor plays vital roles in human connection. Shared laughter creates bonds and eases social tension. Humor can defuse conflict, lighten serious moments, and make difficult messages more palatable. Self-deprecating humor shows humility and approachability. Playful banter builds rapport through shared enjoyment. However, humor must be used sensitively - what's funny varies culturally and individually. Sarcasm and teasing require careful judgment of relationships and contexts. Humor should never punch down or marginalize others. Well-timed, appropriate humor enhances many interactions.)",
    R"(Clear expression requires thoughtful word choice and structure. Concrete language paints vivid pictures: "The red balloon floated upward" versus "It went up." Active voice generally communicates more directly than passive: "The dog chased the ball" versus "The ball was chased." Concise wording often proves more effective than verbosity. Organizing thoughts logically helps listeners follow. Transitional phrases signal relationships between ideas. Precise vocabulary prevents misunderstanding. Regular pauses allow processing time. Volume, pace, and emphasis enhance meaning when used purposefully. These elements combine to create clear, engaging expression.)",
    R"(Digital communication presents unique challenges and opportunities. Text lacks voice tone and body language cues that aid understanding. Emojis and GIFs can help convey emotion and intent. Writing requires extra clarity without immediate feedback. Turn-taking patterns differ from face-to-face conversation. Threading helps track multiple discussion topics. Asynchronous communication allows thoughtful composition but may slow exchanges. Video calls preserve some non-verbal cues but can feel draining. Each digital channel has strengths and limitations. Effective digital communicators adapt their style to the medium while maintaining clear expression.)",
    R"(Emotional intelligence begins with recognizing core emotions: joy, sadness, anger, fear, disgust, and surprise. Each manifests through distinct facial expressions, bodily sensations, and behavioral tendencies. Complex emotions like pride, shame, or contentment blend these basic elements. Emotional awareness involves monitoring our internal state and identifying triggers. Physical signs often precede conscious recognition - racing heart before anxiety, tension before anger. Self-regulation requires understanding these patterns. The ability to name emotions precisely helps manage them effectively. Emotional granularity - having distinct concepts for different emotional states - enhances self-understanding and regulation capacity. Developing emotional vocabulary strengthens our ability to process and communicate feelings effectively.)",
    R"(Emotional regulation involves strategies for managing intensity and expression. The STOP technique helps: Stop, Take a step back, Observe your emotions, Proceed mindfully. Deep breathing activates the parasympathetic nervous system, reducing emotional intensity. Cognitive reframing changes perspective on triggering situations. Setting boundaries protects emotional well-being. The goal isn't suppressing emotions but channeling them constructively. Regular practice of mindfulness strengthens awareness of emotional patterns. Building a toolkit of regulation strategies prepares us for various situations. Recovery time after emotional episodes typically decreases with practice. Self-compassion supports healthy emotional regulation.)",
    R"(Collaborative problem-solving thrives on structured approaches. The first phase involves clearly defining the problem from all perspectives. Stakeholders share their understanding and concerns. Next comes divergent thinking - generating multiple possible solutions without judgment. Brainstorming rules encourage quantity over quality initially. Building on others' ideas creates synergy. The convergent phase evaluates options against agreed criteria. Decision matrices help compare alternatives systematically. Testing solutions on small scale reduces risks. Regular progress reviews allow course correction. Documentation captures learning for future reference. Success requires balancing task focus with relationship maintenance.)",
    R"(Group decision-making combines diverse perspectives and expertise. Consensus building starts with establishing shared goals and decision criteria. The nominal group technique prevents dominant voices from controlling discussion. Round-robin input ensures all perspectives are heard. Silent reflection periods allow processing time. Pareto analysis helps prioritize factors. Breaking complex decisions into components makes them manageable. Devil's advocate roles test assumptions constructively. Time pressure affects decision quality - planning adequate discussion time matters. Groups often make better decisions than individuals when process is well-managed. Clear roles and ground rules support effective group dynamics.)",
    R"(Attachment patterns formed in early relationships influence adult social interactions. Secure attachment enables trust and healthy interdependence. Anxious attachment may drive excessive reassurance seeking. Avoidant attachment can manifest as emotional distance. Understanding our attachment style helps manage relationship patterns. Earned secure attachment develops through consistent positive experiences. Social bonds involve both emotional and practical support. Group cohesion builds through shared experiences and mutual trust. Social identity influences relationship preferences and patterns. Psychological safety enables vulnerability and genuine connection. Regular positive interactions strengthen social bonds over time.)",
    R"(Group dynamics operate through visible and hidden processes. Formal roles distribute responsibilities while informal roles emerge naturally. Status hierarchies develop even in supposedly equal groups. Conformity pressures influence behavior and expression. Group polarization can intensify shared views. Psychological safety enables honest dialogue and creativity. Social loafing decreases with clear individual accountability. Groups develop unique cultures through shared experiences. Size affects participation patterns and relationship formation. Understanding these dynamics helps navigate group situations effectively. Regular reflection improves group functioning. Leadership emerges through behavior rather than just position.)"
    R"(Cultural communication patterns vary significantly across societies. High-context cultures rely heavily on implicit meaning and situational context, while low-context cultures value explicit verbal expression. Power distance affects formality and deference in interactions. Collectivist societies emphasize group harmony and indirect communication, whereas individualist cultures often prefer directness. Time orientation influences pace and punctuality expectations. Some cultures value elaborate greetings and relationship building before business, while others prefer getting straight to the point. Understanding these differences prevents misinterpretation. Cultural humility involves acknowledging our own cultural lens while respecting others' perspectives. Adapting communication style across cultures requires awareness and flexibility.)",
    R"(Effective storytelling follows universal patterns that resonate across cultures. The classic narrative arc builds tension through rising action to climax and resolution. Character development creates emotional investment. Specific details and sensory language make stories vivid and memorable. Pacing controls emotional impact - varying between scene and summary. Stories need conflict or challenge to maintain interest. Personal vulnerability in storytelling builds connection. Metaphor and analogy make complex ideas accessible. Stories bypass resistance and speak directly to emotion. The best stories combine universal themes with unique perspectives. Strategic pauses allow listeners to process and anticipate. Story selection should consider audience and context.)",
    R"(Professional communication requires balancing clarity with diplomacy. Formal settings demand precise language and structured presentation. Email communication needs clear subject lines and concise content. Meeting management involves agenda setting, time management, and following protocols. Giving feedback starts with specific observations before suggesting improvements. Active listening demonstrates professional respect. Documentation provides accountability and reference. Presentations should match audience knowledge and needs. Professional disagreement focuses on issues rather than personalities. Leadership communication balances authority with approachability. Confidentiality maintains professional trust. Regular status updates prevent misunderstandings.)",
    R"(Personal growth emerges through conscious self-reflection and deliberate practice. Learning from experience requires analyzing both successes and failures. Growth mindset sees challenges as opportunities for development. Comfort zone expansion happens gradually through progressive challenges. Feedback integration builds self-awareness and capability. Setting specific, measurable goals guides development. Breaking patterns requires conscious effort and persistence. Social support encourages personal growth journey. Regular self-assessment tracks progress and adjusts direction. Building new habits takes consistent practice over time. Resilience grows through overcoming successive challenges. Celebrating small wins maintains motivation for larger goals.)",
    R"(Nonverbal communication operates through multiple channels simultaneously. Facial micro-expressions reveal brief, unconscious emotional displays. Eye contact patterns signal attention, interest, or dominance. Personal space preferences vary culturally and contextually. Gesture clusters provide more reliable meaning than single gestures. Body orientation shows engagement or distance. Touch appropriateness varies by relationship and culture. Paralinguistics - vocal qualities beyond words - convey emotional meaning. Clothing and appearance send social signals. Environmental factors influence nonverbal behavior. Timeline of nonverbal signals helps predict behavior. Congruence between verbal and nonverbal messages builds trust.)",
    R"(Advanced body language interpretation considers baseline behavior and clusters. Posture changes indicate emotional shifts - expansion showing confidence, contraction suggesting uncertainty. Hand movements near face often signal stress or deception. Mirroring behavior naturally occurs in rapport. Pacifying behaviors release tension through self-touch. Blocking behaviors create psychological barriers when uncomfortable. Authentic smiles involve eye muscles unlike social smiles. Territorial markers show psychological ownership of space. Preening behaviors indicate attraction or status display. Emblematic gestures carry specific cultural meanings. Reading body language requires considering context and cultural norms.)",
    R"(Cultural diversity enriches collective understanding through varied perspectives. Traditions carry accumulated wisdom while adapting to present needs. Value systems influence behavior and decision-making preferences. Cultural identity develops through both inheritance and choice. Intercultural competence grows through exposure and reflection. Stereotypes oversimplify complex cultural realities. Cultural appropriation differs from respectful cultural exchange. Globalization creates new hybrid cultural forms. Heritage preservation maintains cultural continuity. Cultural code-switching shows adaptability across contexts. Diversity within cultures matches diversity between cultures. Cultural evolution happens through both internal development and external influence.)",
    R"(Persuasion psychology relies on core principles of human behavior. The reciprocity principle creates obligation to return favors. Social proof influences people to follow others' actions. Commitment and consistency drive people to align with previous statements. Authority figures impact belief and behavior adoption. Scarcity increases perceived value and urgency. Liking enhances persuasive impact - similarity, compliments, and cooperation build rapport. The contrast principle affects perception through comparison. Timing of requests influences compliance probability. Building credibility requires expertise demonstration and trustworthiness. Ethical persuasion considers others' genuine interests.)",
    R"(Information processing shapes conversation comprehension and memory. Attention filters select relevant information from environmental input. Working memory juggles multiple conversation elements simultaneously. Schema activation helps interpret new information through existing knowledge frameworks. Cognitive load affects processing capacity - stress and distraction reduce effectiveness. Chunking information aids memory retention. The serial position effect influences recall of conversation sequences. Elaborative rehearsal strengthens memory through meaningful connections. Retrieval practice enhances long-term retention. Metacognition monitors understanding and guides conversation strategy. Multi-modal processing enriches comprehension and recall.)",
    R"(Conflict resolution strategies vary by situation and relationship context. The Thomas-Kilmann model identifies five approaches: competing, accommodating, avoiding, compromising, and collaborating. Interest-based negotiation focuses on underlying needs rather than positions. Active listening during conflict reduces defensive reactions. Reframing helps shift perspective and find solutions. Separating people from problems enables objective problem-solving. BATNA understanding strengthens negotiation position. Win-win solutions require creative option generation. Timing affects conflict resolution success - some conflicts need cooling periods. Power dynamics influence conflict approach selection. Regular maintenance prevents conflict escalation.)",
    R"(Group facilitation requires managing both task and process elements. Setting clear objectives guides productive discussion. Ground rules establish behavioral expectations. Time management balances participation with progress. Visual aids support understanding and focus. Parking lot technique manages off-topic issues. Process checking ensures group alignment. Energy management maintains productive engagement. Bridging techniques connect different viewpoints. Summarizing captures progress and confirms understanding. Decision-making methods match situation requirements. Closure activities consolidate learning and commitment. Documentation supports implementation follow-through.)",
    R"(Emotional contagion influences group dynamics and relationships. Mirror neurons respond to others' emotional displays. Mood synchronization occurs naturally in close interactions. Leadership emotions particularly impact group climate. Positive emotional spirals build collaborative energy. Negative emotions spread faster than positive ones. Emotional boundaries prevent unhealthy absorption. Recovery rituals help reset emotional state. Group emotional intelligence develops through practice. Emotional climate affects creativity and problem-solving. Managing emotional contagion requires awareness and regulation skill. Individual emotional stability contributes to group resilience.)",
    R"(Relationship development follows predictable stage progression. Initial attraction based on surface qualities leads to deeper exploration. Self-disclosure gradually increases with trust development. Relationship rules evolve through explicit and implicit negotiation. Maintenance behaviors sustain relationship health. Role expectations influence interaction patterns. Attachment styles affect relationship development trajectory. Identity changes occur through relationship influence. Power balancing requires ongoing adjustment. Relationship boundaries adapt to changing circumstances. Growth opportunities arise through challenge navigation. Long-term relationships require active renewal commitment.)",
    R"(Cognitive biases systematically affect decision making and perception. Confirmation bias leads people to seek information supporting existing beliefs. The availability heuristic causes overestimation of easily recalled events' frequency. Anchoring affects judgments through initial reference points. The fundamental attribution error overemphasizes personality versus situational factors. Status quo bias creates resistance to change from current states. The halo effect generalizes positive traits across unrelated characteristics. Hindsight bias makes past events seem more predictable than they were. Overconfidence bias leads to unrealistic assessment of abilities. Recognizing these biases enables more objective thinking.)",
    R"(Change management follows predictable psychological patterns. Initial resistance stems from fear of loss or incompetence. The change curve progresses through denial, anger, depression, and acceptance. Creating urgency motivates initial movement. Clear vision provides direction and purpose. Small wins build momentum and confidence. Support systems help maintain progress during difficulties. New habits require consistent practice over time. Change leaders must model desired behaviors. Celebrating progress reinforces positive movement. Regular feedback enables course correction. Sustainability planning prevents reversion to old patterns.)",
    R"(Creative thinking employs specific cognitive strategies. Divergent thinking generates multiple possibilities without judgment. Lateral thinking approaches problems from unexpected angles. Analogical reasoning finds insights through comparison. Combinatorial creativity connects existing elements in new ways. Incubation periods allow unconscious processing. Constraint removal exercises expand possibility thinking. Perspective shifting generates new viewpoints. Environmental factors influence creative output. Group creativity requires psychological safety. Creative blocks often stem from premature judgment. Regular practice enhances creative capacity.)",
    R"(Stress response mechanisms affect cognitive and social functioning. The sympathetic nervous system activates fight-flight-freeze responses. Cortisol affects memory formation and recall. Chronic stress impairs decision-making ability. Stress contagion spreads through groups. Resilience builds through controlled stress exposure. Recovery periods enable resource replenishment. Social support buffers stress effects. Cognitive reappraisal changes stress perception. Problem-focused coping targets stressor reduction. Emotion-focused coping manages stress response. Regular stress management prevents cumulative damage.)",
    R"(Learning styles influence information processing preferences. Visual learners prioritize imagery and spatial organization. Auditory learners process through sound and discussion. Kinesthetic learners engage through movement and touch. Reading/writing preference focuses on text interaction. Multiple modality engagement enhances learning effectiveness. Style flexibility develops through practice. Environmental factors affect learning efficiency. Meta-learning involves understanding personal learning patterns. Learning preferences may vary by subject or context. Matching teaching to learning styles improves outcomes. Regular self-assessment refines learning strategies.)",
    R"(Motivation arises from both intrinsic and extrinsic factors. Autonomy, mastery, and purpose drive internal motivation. External rewards can undermine intrinsic motivation. Goal-setting affects effort direction and persistence. Achievement motivation balances success pursuit with failure avoidance. Flow states emerge from skill-challenge balance. Progress monitoring maintains motivation. Social comparison influences achievement behavior. Value expectancy determines effort investment. Attribution patterns affect future motivation. Regular goal review maintains engagement. Building motivation requires progressive challenge.)",
    R"(Rhetorical strategies structure persuasive communication. Ethos establishes speaker credibility and authority. Pathos engages emotional connection and resonance. Logos presents logical reasoning and evidence. Strategic storytelling illustrates key points memorably. Audience analysis guides message adaptation. Rhetorical questions engage active processing. Repetition reinforces key messages. Contrast highlights important distinctions. Metaphor makes abstract concepts concrete. Timing affects message impact. Structure supports comprehension and retention. Regular practice refines rhetorical skill.)",
    R"(Crisis communication requires rapid, clear response. Initial assessment determines response scope and urgency. Stakeholder analysis identifies key audiences. Message consistency maintains credibility. Transparency builds trust during uncertainty. Regular updates prevent information vacuum. Empathy acknowledges emotional impact. Action steps provide clear direction. Rumor management prevents misinformation spread. Documentation supports future analysis. Recovery planning begins during crisis. Leadership visibility provides reassurance. Regular preparation enables effective crisis response.)",
    R"(Collective intelligence emerges through structured interaction. Diversity enhances problem-solving capability. Aggregation mechanisms combine individual contributions. Decision rules affect outcome quality. Information sharing patterns influence collective performance. Social influence affects independent judgment. Group size impacts participation dynamics. Technology platforms enable distributed collaboration. Feedback loops improve system performance. Incentive alignment affects contribution quality. Regular evaluation refines collective processes. Leadership facilitates rather than directs.)",
    R"(Memory processes involve encoding, storage, and retrieval. Attention filters determine initial encoding. Elaborative rehearsal strengthens memory formation. Emotional significance enhances retention. Pattern recognition aids information organization. Retrieval cues activate stored information. Context affects recall accessibility. Interference impacts memory accuracy. Reconsolidation enables memory updating. Distributed practice enhances long-term retention. Memory strategies improve performance. Regular review maintains accessibility.)",
    R"(Intergenerational communication bridges experience gaps. Value differences reflect historical context. Communication style preferences vary by generation. Technology comfort affects interaction channels. Mentoring relationships benefit both parties. Stereotype awareness prevents misunderstanding. Common ground building creates connection. Respect acknowledgment enhances engagement. Flexibility enables effective collaboration. Regular dialogue builds understanding. Shared projects create learning opportunities. Knowledge transfer requires active engagement.)",
    R"(Written communication differs structurally from oral exchange. Message permanence requires greater precision. Organization patterns guide reader comprehension. Paragraph structure develops single ideas completely. Transitions connect ideas coherently. Audience analysis guides style selection. Revision improves clarity and concision. Format affects message reception. Document design enhances readability. Active voice strengthens directness. Punctuation guides interpretation. Written feedback requires special sensitivity. Regular practice develops written fluency. Style guides ensure consistency. Digital formats demand adaptation.)",
    R"(Mindset patterns influence learning and development. Growth mindset sees ability as developable through effort. Fixed mindset views capabilities as static. Challenge response reveals mindset orientation. Failure interpretation affects future behavior. Effort attribution encourages persistence. Process praise supports growth orientation. Learning goals outperform performance goals. Mindset flexibility develops through experience. Environmental cues affect mindset activation. Leadership mindset influences organizational culture. Regular reflection develops mindset awareness. Personal narratives reveal mindset patterns.)",
    R"(Information overload affects cognitive processing capacity. Attention filtering mechanisms prevent system overwhelm. Multitasking reduces performance quality. Decision fatigue depletes cognitive resources. Prioritization strategies manage input volume. Organization systems reduce cognitive load. Recovery periods restore processing capacity. Environmental design affects focus ability. Technology management prevents distraction. Routine automation preserves cognitive resources. Regular breaks maintain effectiveness. Simplification strategies reduce complexity. Information architecture guides processing.)",
    R"(Social influence operates through multiple channels. Authority triggers automatic compliance responses. Social proof guides behavior in uncertain situations. Commitment drives consistency with past actions. Scarcity increases perceived value. Liking enhances persuasive impact. Reciprocity creates social obligation. Contrast affects judgment and decision. Timing influences receptivity. Environmental cues trigger behavior patterns. Influence awareness enables conscious choice. Regular analysis reveals influence patterns. Ethical influence considers mutual benefit.)",
    R"(Team dynamics emerge through interaction patterns. Role clarity enables effective coordination. Trust develops through demonstrated reliability. Communication norms affect collaboration quality. Conflict resolution skills prevent escalation. Decision processes balance efficiency with inclusion. Leadership styles affect team climate. Goal alignment drives coordinated action. Accountability maintains performance standards. Recognition reinforces positive behavior. Regular feedback enables adjustment. Team learning requires psychological safety. Performance monitoring enables improvement.)",
    R"(Perception filtering shapes experience interpretation. Mental models guide understanding. Expectation affects observation. Pattern recognition enables quick processing. Selective attention focuses limited resources. Perceptual defenses protect existing beliefs. Cultural frameworks influence interpretation. Previous experience guides understanding. Context affects meaning construction. Perception checking prevents misunderstanding. Regular reflection increases awareness. Perspective taking expands understanding. Filter awareness enables conscious choice.)",
    R"(Innovation processes combine creativity with implementation. Problem definition guides solution search. Ideation generates multiple possibilities. Selection criteria guide choice. Prototyping tests concept viability. Implementation planning ensures execution. Resistance management enables adoption. Feedback loops guide refinement. Scale considerations affect rollout. Documentation captures learning. Regular review maintains progress. Success measurement guides adjustment. Innovation culture supports experimentation. Resource allocation enables development.)",
    R"(Leadership communication balances clarity with inspiration. Vision communication provides direction. Goal setting guides effort allocation. Feedback develops capability. Recognition reinforces desired behavior. Presence communicates attention and value. Listening demonstrates respect. Question technique guides thinking. Story sharing builds connection. Crisis communication maintains confidence. Regular dialogue builds understanding. Leadership style affects climate. Communication consistency builds trust. Adaptive communication meets situation needs.)",
    R"(Negotiation dynamics involve multiple influences. Power balance affects interaction. Interest identification guides solution search. Option generation expands possibility. Criteria selection guides choice. Commitment building ensures follow-through. Relationship maintenance supports agreement. Communication clarity prevents misunderstanding. Timing affects receptivity. Preparation improves outcomes. Regular check-in maintains progress. Trust building enables collaboration. Alternative availability affects leverage. Strategy selection matches situation.)",
    R"(Decision-making processes integrate multiple factors. Information gathering provides foundation. Analysis reveals patterns and relationships. Evaluation applies judgment criteria. Bias awareness enables objectivity. Emotion recognition affects choice. Time pressure influences quality. Group dynamics affect outcomes. Risk assessment guides action. Implementation planning ensures execution. Regular review enables adjustment. Learning capture improves process. Decision documentation enables review. Stakeholder consideration ensures support. Context affects strategy selection.)",
    R"(Emotional intelligence development follows systematic progression. Self-awareness forms the foundation for growth. Emotion recognition includes physical and mental signals. Trigger identification enables proactive management. Response patterns reveal underlying beliefs. Regulation strategies match situation needs. Empathy builds through perspective taking. Social skills develop through practice. Feedback integration guides improvement. Recovery processes restore balance. Regular assessment tracks progress. Development planning guides growth. Support systems enable sustained change. Situation analysis guides strategy selection.)",
    R"(Pattern recognition underlies learning and adaptation. Neural networks strengthen through repeated activation. Schema development organizes knowledge structures. Category formation enables efficient processing. Exception handling refines understanding. Pattern interruption signals importance. Recognition speed increases with practice. Context sensitivity improves accuracy. Pattern transfer enables new application. Regular practice strengthens recognition. Pattern awareness enables conscious choice. Learning transfer requires pattern understanding. Environmental cues trigger pattern activation. Pattern flexibility enables adaptation.)",
    R"(Group facilitation requires multiple skill integration. Energy management maintains engagement. Participation balance ensures inclusion. Focus maintenance drives progress. Conflict management prevents disruption. Decision process guides choice. Time management ensures completion. Documentation captures learning. Process intervention maintains effectiveness. Regular assessment enables adjustment. Skill development requires practice. Tool selection matches need. Environment design supports purpose. Preparation enables smooth execution. Feedback integration guides improvement.)",
    R"(Knowledge management systems support collective learning. Information organization enables access. Classification systems guide storage. Retrieval systems enable use. Sharing processes enable distribution. Security measures protect assets. Update processes maintain currency. Archive systems preserve history. Search capability enables finding. Regular maintenance ensures function. User interface affects adoption. Integration enables connection. System design matches need. Implementation planning ensures success. Evaluation guides improvement.)",
    R"(Identity formation influences interaction patterns. Self-concept affects behavior choice. Role adoption guides action. Value alignment affects commitment. Belief systems shape interpretation. Experience integration builds understanding. Identity flexibility enables adaptation. Social influence affects development. Culture shapes identity formation. Regular reflection increases awareness. Growth experiences enable development. Support systems enable change. Choice awareness enables direction. Identity expression matches context.)",
    R"(Time perception affects interaction and planning. Cultural differences influence timing. Urgency perception affects priority. Schedule density impacts quality. Recovery periods enable sustainability. Rhythm patterns affect energy. Timing sensitivity improves outcomes. Preparation time enables quality. Response time affects relationship. Regular assessment enables adjustment. Pattern awareness guides planning. Flexibility enables adaptation. Time management matches need. Balance maintains effectiveness.)",
    R"(Network development requires strategic attention. Relationship building creates connection. Value exchange sustains engagement. Trust development enables depth. Communication maintenance sustains connection. Boundary management prevents overwhelm. Network diversity enables resilience. Regular contact maintains strength. Support exchange builds commitment. Growth opportunities enable development. Review processes ensure value. Strategy adjustment meets need. Network analysis guides action. Resource investment matches return.)",
    R"(Learning transfer enables broader application. Principle extraction guides transfer. Context analysis enables application. Practice opportunity enables development. Feedback integration guides improvement. Support systems enable success. Transfer barriers require attention. Strategy selection matches need. Regular assessment tracks progress. Application planning ensures success. Review processes capture learning. Development planning guides growth. Transfer motivation affects success. Environment support enables application.)",
    R"(Change resistance reflects multiple factors. Loss perception drives resistance. Uncertainty creates anxiety. Control loss threatens security. Competence challenge creates fear. Support needs affect acceptance. Information needs require attention. Time pressure affects adaptation. Regular communication maintains progress. Success evidence builds confidence. Recognition reinforces change. Planning enables preparation. Strategy selection matches need. Resistance management enables progress.)",
    R"(Virtual interaction creates unique dynamics. Technology mediation affects connection. Presence creation requires attention. Engagement maintenance needs strategy. Communication clarity prevents confusion. Relationship building requires intention. Trust development takes time. Regular contact maintains connection. Format selection matches purpose. Preparation enables effectiveness. Tool selection matches need. Practice improves performance. Strategy adaptation meets situation. Environment design supports function.)",
    R"(Metacognition enhances learning effectiveness. Self-monitoring tracks understanding. Strategy selection guides approach. Progress evaluation enables adjustment. Learning patterns reveal preferences. Reflection deepens understanding. Knowledge gaps guide focus. Question generation drives exploration. Understanding assessment guides action. Regular review maintains progress. Development planning enables growth. Skill practice strengthens ability. Awareness cultivation improves effectiveness. Strategy adaptation matches situation.)",
    R"(Attention management determines processing quality. Focus direction guides learning. Distraction management maintains effectiveness. Energy allocation affects performance. Priority setting guides attention. Environment design supports focus. Recovery periods restore capacity. Regular assessment enables adjustment. Strategy selection matches need. Practice strengthens control. Pattern awareness enables choice. Tool selection supports purpose. Flexibility enables adaptation. Balance maintains effectiveness.)",
    R"(Social synchronization occurs naturally in groups. Rhythm matching shows connection. Movement coordination demonstrates attunement. Energy levels affect synchronization. Group size influences dynamics. Leadership emergence affects pattern. Regular interaction strengthens synchronization. Environment affects coordination. Practice improves alignment. Pattern awareness enables choice. Strategy selection matches need. Balance maintains effectiveness. Flexibility enables adaptation. Analysis guides improvement.)",
    R"(Information synthesis combines multiple sources. Pattern recognition enables integration. Connection identification creates meaning. Framework development organizes understanding. Perspective integration broadens view. Regular review deepens comprehension. Practice improves ability. Strategy selection guides approach. Tool usage supports process. Environment design enables focus. Balance maintains effectiveness. Flexibility allows adaptation. Analysis guides improvement. Development planning enables growth.)",
    R"(Behavioral economics reveals decision patterns. Choice architecture affects outcomes. Default options guide behavior. Loss aversion influences decisions. Immediate rewards drive action. Social proof guides choice. Scarcity increases value. Anchoring affects judgment. Regular analysis reveals patterns. Strategy selection matches need. Environment design supports purpose. Practice improves awareness. Flexibility enables adaptation. Balance maintains effectiveness.)",
    R"(Cultural intelligence enables effective interaction. Framework understanding guides approach. Behavior adaptation shows respect. Language sensitivity prevents offense. Custom recognition demonstrates awareness. Regular interaction builds understanding. Practice improves ability. Strategy selection matches need. Tool usage supports learning. Environment design enables growth. Balance maintains effectiveness. Flexibility allows adaptation. Analysis guides improvement. Development planning enables progress.)",
    R"(Memory consolidation requires multiple processes. Encoding strength affects retention. Storage organization enables retrieval. Practice strengthens connections. Emotion affects memory formation. Context influences recall. Regular review maintains access. Strategy selection guides approach. Tool usage supports process. Environment design enables focus. Balance maintains effectiveness. Flexibility allows adaptation. Analysis guides improvement. Development planning enables growth.)",
    R"(Group cohesion develops through shared experience. Trust building requires time. Goal alignment creates unity. Communication patterns affect connection. Conflict resolution strengthens bonds. Regular interaction maintains cohesion. Practice improves dynamics. Strategy selection matches need. Tool usage supports process. Environment design enables growth. Balance maintains effectiveness. Flexibility allows adaptation. Analysis guides improvement. Development planning enables progress.)",
    R"(Adaptive leadership responds to situation needs. Context analysis guides approach. Strategy selection matches need. Communication clarity enables understanding. Support provision maintains progress. Regular assessment enables adjustment. Practice improves ability. Tool usage supports process. Environment design enables growth. Balance maintains effectiveness. Flexibility allows adaptation. Analysis guides improvement. Development planning enables progress. Pattern recognition guides action.)",
    R"(Cognitive load management enables effective processing. Task complexity affects demand. Information organization reduces load. Strategy selection guides approach. Tool usage supports process. Environment design enables focus. Regular assessment allows adjustment. Practice improves capacity. Balance maintains effectiveness. Flexibility enables adaptation. Analysis guides improvement. Development planning enables growth. Pattern recognition guides action. Support systems enable success.)",
    R"(Active listening involves multiple cognitive processes. Attention focusing excludes distractions. Message processing extracts meaning. Non-verbal observation provides context. Feedback provision demonstrates engagement. Question formulation deepens understanding. Empathy expression builds connection. Paraphrasing confirms comprehension. Regular practice improves skill. Strategy adaptation meets situation. Tool selection supports process. Environment design enables focus. Analysis guides improvement. Development planning enables growth.)",
    R"(Psychological safety enables group innovation. Trust development requires consistency. Risk tolerance encourages participation. Failure acceptance promotes learning. Feedback reception improves process. Leadership behavior shapes climate. Regular assessment maintains standards. Practice strengthens culture. Strategy selection matches need. Environment design supports purpose. Balance maintains effectiveness. Flexibility enables adaptation. Analysis guides improvement. Support systems enable growth.)",
    R"(Mental models shape perception and action. Framework development organizes knowledge. Experience integration updates models. Assumption testing improves accuracy. Model sharing enables collaboration. Regular review refines understanding. Practice improves application. Strategy selection guides approach. Tool usage supports process. Environment design enables learning. Balance maintains effectiveness. Flexibility allows adaptation. Analysis guides improvement. Development planning enables growth.)",
    R"(Conflict transformation changes interaction patterns. Source identification guides approach. Position exploration reveals interests. Solution generation expands options. Agreement building creates commitment. Implementation planning ensures follow-through. Regular review maintains progress. Practice improves skill. Strategy selection matches need. Environment design supports process. Balance maintains effectiveness. Flexibility enables adaptation. Analysis guides improvement. Support systems enable success.)",
    R"(Information architecture structures knowledge access. Organization systems enable retrieval. Classification guides storage. Navigation design supports use. Search capability enables finding. Regular maintenance ensures function. Practice improves efficiency. Strategy selection matches need. Tool usage supports process. Environment design enables access. Balance maintains effectiveness. Flexibility allows adaptation. Analysis guides improvement. Development planning enables growth.)",
    R"(Social learning occurs through observation. Model behavior guides development. Attention focusing enables learning. Pattern recognition supports adoption. Practice strengthens capability. Regular feedback guides improvement. Strategy selection matches need. Tool usage supports process. Environment design enables growth. Balance maintains effectiveness. Flexibility allows adaptation. Analysis guides improvement. Development planning enables progress. Support systems enable success.)",
    R"(Decision fatigue affects judgment quality. Energy management maintains capacity. Priority setting guides focus. Recovery periods restore function. Strategy selection matches need. Environment design supports process. Regular assessment enables adjustment. Practice improves resilience. Tool usage supports management. Balance maintains effectiveness. Flexibility allows adaptation. Analysis guides improvement. Development planning enables growth. Support systems enable success.)",
    R"(Cognitive flexibility enables adaptive response. Perspective shifting expands options. Strategy variation increases effectiveness. Context sensitivity guides approach. Regular practice improves ability. Tool selection supports process. Environment design enables growth. Balance maintains effectiveness. Flexibility allows adaptation. Analysis guides improvement. Development planning enables progress. Pattern recognition guides action. Support systems enable success. Learning integration enables development.)",
    R"(Collaborative problem-solving combines multiple perspectives. Input gathering expands understanding. Analysis integration creates insight. Solution generation expands options. Implementation planning ensures success. Regular review maintains progress. Practice improves process. Strategy selection matches need. Tool usage supports collaboration. Environment design enables effectiveness. Balance maintains function. Flexibility allows adaptation. Analysis guides improvement. Support systems enable success.)",
    R"(Performance optimization requires systematic approach. Goal setting guides direction. Measurement enables tracking. Feedback guides adjustment. Strategy selection matches need. Environment design supports performance. Regular assessment maintains progress. Practice improves capability. Tool usage supports process. Balance maintains effectiveness. Flexibility allows adaptation. Analysis guides improvement. Development planning enables growth. Support systems enable success.)"
};

const string raw_data_test =
R"(During an international conference on innovative technologies, diverse participants from different cultural backgrounds gathered in small discussion groups. As the facilitator approached one particularly engaged group, she noticed subtle shifts in body language and conversational dynamics. The way people were positioning themselves, their facial micro-expressions, and their turn-taking patterns revealed interesting patterns of)";

wstring utf8_to_wstr(const string& utf8) {
    wstring_convert<std::codecvt_utf8_utf16<wchar_t>> wcu8;
    return wcu8.from_bytes(utf8);
}
string wstr_to_utf8(const wstring& utf16) {
    wstring_convert<std::codecvt_utf8_utf16<wchar_t>> wcu8;
    return wcu8.to_bytes(utf16);
}
string ansi_to_utf8(const string& ansi_str) {
    wstring_convert<std::codecvt_utf8<wchar_t>> converter;
    wstring wide_chars = wstring_convert<std::codecvt<wchar_t, char, std::mbstate_t>, wchar_t>{}.from_bytes(ansi_str);
    return converter.to_bytes(wide_chars);
}

void write_raw_data(const string& file_path, const std::vector<string>& data = raw_data) {
    ofstream file(file_path, std::ios::binary);
    if (file.is_open()) {
        for (const auto& document : data) file << ansi_to_utf8(document) << "\n";
        file.close();
        cout << "raw data written to " << file_path << endl;
    } else {
        cerr << "Unable to open file: " << file_path << endl;
    }
}

#endif // DATA_H